name: Automatic tests on pull requests

on:
  pull_request:
  push:
    branches: 
      - master
      - development

jobs:
  test:
    name: Running Units Jest Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: yarn install
    - name: Test
      run: yarn test:badges
